trigger:
- main

variables:
  # Reference to Variable Groups linked to Azure Key Vault and manual variables
  - group: navique-vault-secrets 
  - group: navique-infra-vars    
  
  # Service Connection for Docker Registry (ACR)
  - name: dockerRegistryServiceConnection
    value: '37b4ae59-4492-44b1-af46-33ee887f636c'
    
  # Service Connection for Azure Resource Manager (ARM) - used for CLI commands
  - name: azureArmServiceConnection
    value: 'Azure subscription 1 (6a7ef46a-5802-4c50-9528-616be0af6fed)'
    
  # Container Registry details
  - name: imageRepository
    value: 'naviquesparkpipeline'
  - name: containerRegistry
    value: 'acrnavique2026.azurecr.io'
  - name: tag
    value: '$(Build.BuildId)'

stages:
# --- STAGE 1: Continuous Integration (Build & Test) ---
- stage: Build_and_Push
  displayName: "CI: Build, Test & Push"
  jobs:
  - job: CI_Job
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - script: pip install pyspark pytest
      displayName: 'Install dependencies for Unit Testing'
      
    - script: pytest tests/
      displayName: 'Execute PySpark Unit Tests'
      
    - task: Docker@2
      displayName: "Build and Push Docker Image to ACR"
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

# --- STAGE 2: Deployment to TEST Environment ---
- stage: Deploy_Test
  displayName: "CD: Deploy to TEST"
  dependsOn: Build_and_Push
  jobs:
  - deployment: Test_Deployment
    environment: 'Test' # Requires 'Permit' access in Azure DevOps UI on first run
    pool: { vmImage: 'ubuntu-latest' }
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: "Provision ACI for Test Environment"
            inputs:
              azureSubscription: $(azureArmServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Fetch ACR Admin Credentials dynamically to avoid hardcoding secrets
                # The 'issecret=true' flag ensures the password is masked in the logs
                RAW_PASS=$(az acr credential show --name acrnavique2026 --query "passwords[0].value" -o tsv)
                echo "##vso[task.setvariable variable=ACR_PASSWORD;issecret=true]$RAW_PASS"

                # Create Azure Container Instance (ACI) and pass environment variables
                az container create \
                  --resource-group rg-navique-challenge \
                  --name spark-pipeline-test \
                  --image $(containerRegistry)/$(imageRepository):$(tag) \
                  --registry-login-server $(containerRegistry) \
                  --registry-username acrnavique2026 \
                  --registry-password "$RAW_PASS" \
                  --os-type Linux \
                  --cpu 1 \
                  --memory 2 \
                  --restart-policy Never \
                  --environment-variables \
                    ENV="TEST" \
                    _JAVA_OPTIONS="-Duser.home=/tmp -Duser.name=root" \
                    HADOOP_USER_NAME="root" \
                  --secure-environment-variables \
                    AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)" \
                    AZURE_CLIENT_SECRET="$(AZURE-CLIENT-SECRET)" \
                    AZURE_TENANT_ID="$(AZURE_TENANT_ID)"\

# --- STAGE 3: Deployment to PRODUCTION Environment ---
- stage: Deploy_Prod
  displayName: "CD: Deploy to PROD"
  dependsOn: Deploy_Test
  condition: succeeded() # Only runs if Test deployment is successful
  jobs:
  - deployment: Prod_Deployment
    environment: 'Production' # Manual Approval should be configured for this environment
    pool: { vmImage: 'ubuntu-latest' }
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: "Provision ACI for Production Environment"
            inputs:
              azureSubscription: $(azureArmServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Dynamic credential retrieval for Production ACR access
                RAW_PASS=$(az acr credential show --name acrnavique2026 --query "passwords[0].value" -o tsv)
                echo "##vso[task.setvariable variable=ACR_PASSWORD;issecret=true]$RAW_PASS"
                export ACR_PASSWORD=$RAW_PASS

                # Create Production Instance with PROD configuration
                az container create \
                  --resource-group rg-navique-challenge \
                  --name spark-pipeline-prod \
                  --image $(containerRegistry)/$(imageRepository):$(tag) \
                  --registry-login-server $(containerRegistry) \
                  --registry-username acrnavique2026 \
                  --registry-password "$RAW_PASS" \
                  --os-type Linux \
                  --cpu 1 \
                  --memory 2 \
                  --restart-policy Never \
                  --environment-variables \
                    ENV="PROD" \
                    _JAVA_OPTIONS="-Duser.home=/tmp -Duser.name=root" \
                    HADOOP_USER_NAME="root" \
                  --secure-environment-variables \
                    AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)" \
                    AZURE_CLIENT_SECRET="$(AZURE-CLIENT-SECRET)" \
                    AZURE_TENANT_ID="$(AZURE_TENANT_ID)"