# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '37b4ae59-4492-44b1-af46-33ee887f636c'
  imageRepository: 'naviquesparkpipeline'
  containerRegistry: 'acrnavique2026.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    # 1. Install dependencies required for testing
    - script: |
        python -m pip install --upgrade pip
        pip install pyspark pytest
      displayName: 'Install test dependencies'

    # 2. Execute PySpark unit tests to ensure code quality
    - script: |
        pytest tests/
      displayName: 'Run PySpark Unit Tests'

    # 3. Build and push the Docker image (ONLY if tests pass successfully)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: AzureCLI@2
      displayName: 'CD: Run Spark Pipeline in Azure Container Instances (Serverless)'
      inputs:
        azureSubscription: $(dockerRegistryServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
            echo "Deploying and running the container in ACI..."
            az container create \
              --resource-group rg-navique-challenge \
              --name navique-spark-run \
              --image acrnavique2026.azurecr.io/naviquesparkpipeline:latest \
              --registry-login-server acrnavique2026.azurecr.io \
              --registry-username $(acr_username) \
              --registry-password $(acr_password) \
              --restart-policy Never \
              --environment-variables \
                AZURE_TENANT_ID="$(AZURE_TENANT_ID)" \
                AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)" \
                AZURE_CLIENT_SECRET="$(AZURE_CLIENT_SECRET)"