trigger:
- main

variables:
- group: navique-vault-secrets # Linked to Key Vault
- name: dockerRegistryServiceConnection
  value: '37b4ae59-4492-44b1-af46-33ee887f636c'
- name: imageRepository
  value: 'naviquesparkpipeline'
- name: containerRegistry
  value: 'acrnavique2026.azurecr.io'
- name: tag
  value: '$(Build.BuildId)'

stages:
# --- STAGE 1: Continuous Integration (Build & Test) ---
- stage: Build_and_Push
  displayName: "CI: Build, Test & Push"
  jobs:
  - job: CI_Job
    pool: { vmImage: 'ubuntu-latest' }
    steps:
    - script: pip install pyspark pytest
      displayName: 'Install Test Dependencies'
    - script: pytest tests/
      displayName: 'Run Unit Tests'
    - task: Docker@2
      displayName: "Build and Push Image"
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

# --- STAGE 2: Deployment to TEST Environment ---
- stage: Deploy_Test
  displayName: "CD: Deploy to TEST"
  dependsOn: Build_and_Push
  jobs:
  - deployment: Test_Deployment
    environment: 'Test' # Ensure this environment exists in Azure DevOps
    pool: { vmImage: 'ubuntu-latest' }
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(dockerRegistryServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az container create \
                  --resource-group rg-navique-challenge \
                  --name spark-pipeline-test \
                  --image $(containerRegistry)/$(imageRepository):$(tag) \
                  --restart-policy Never \
                  --environment-variables \
                    ENV="TEST" \
                    AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)" \
                    AZURE_CLIENT_SECRET="$(AZURE-CLIENT-SECRET)" \
                    AZURE_TENANT_ID="$(AZURE_TENANT_ID)"

# --- STAGE 3: Deployment to PRODUCTION Environment ---
- stage: Deploy_Prod
  displayName: "CD: Deploy to PROD"
  dependsOn: Deploy_Test
  condition: succeeded()
  jobs:
  - deployment: Prod_Deployment
    environment: 'Production' # Add Manual Approval check here in DevOps Portal
    pool: { vmImage: 'ubuntu-latest' }
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(dockerRegistryServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az container create \
                  --resource-group rg-navique-challenge \
                  --name spark-pipeline-prod \
                  --image $(containerRegistry)/$(imageRepository):$(tag) \
                  --restart-policy Never \
                  --environment-variables \
                    ENV="PROD" \
                    AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)" \
                    AZURE_CLIENT_SECRET="$(AZURE-CLIENT-SECRET)" \
                    AZURE_TENANT_ID="$(AZURE_TENANT_ID)"